### ISSUE TITLE
Database conformity

### ISSUE THREAD

**Issue by snapo** [DongyangY/StockPrediction#1]
Hi,
i did just test your project (btw. amazing work) and have the following problems...

com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'GOOG-2015-08-13' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.Util.getInstance(Util.java:360)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:971)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
        at stockforecaster.BayesianPredictor.ShortTermPredictAll(BayesianPredictor.java:183)
        at stockforecaster.StockForecaster.<init>(StockForecaster.java:45)
        at stockforecaster.StockForecaster.main(StockForecaster.java:75)
database operation error 2.

after this it stops doing anything anymore ;=)

also i see that because you use OSX you dont use case sensitive database names / table names... i did try to fix it with 

/etc/mysql/my.cnf 

Under [mysqld] add "lower_case_table_names = 1"  

after that the problem is that the java files dont check if specific primary keys already exist.
i did try to edit all javafiles , recompile them, drop the table, import the default tables start it new.

after that the problem is that forecast.php does not work because java does not fill in the necessary tables. Some tables stay empty.

Here is my step by step guide what i did to get it running on ubuntu 14.04:

`
#1. Install Oracle JDK 8, git, vim

Ref: https://www.digitalocean.com/community/tutorials/how-to-install-java-on-ubuntu-with-apt-get
apt-get install python-software-properties
add-apt-repository ppa:webupd8team/java
yes
apt-get update
apt-get install oracle-java8-installer
# java -version

java version "1.8.0_101"
..
# apt-get install vim
# apt-get install git
#2. Install mysql 5.6 and enable "lower_case_table_names=1" 

Ref: https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-14-04
# apt-get install mysql-server-5.6

It will ask to set mysql root password. Do it. Save the pass to /root/mysql_pwd 
E.g. "password123" as StockPrediction uses. 
# mysql_secure_installation

 Change the root password? [Y/n] n !already set
 Remove anonymous users? [Y/n]
 Disallow root login remotely? [Y/n] 
 Remove test database and access to it? [Y/n] n
 Reload privilege tables now? [Y/n]

 # cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf
 # mysql_install_db

Test mysql:
# MYSQL_PWD=$(cat /root/mysql_pwd) mysql -u root

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 48
Server version: 5.6.31-0ubuntu0.14.04.2 (Ubuntu)
[..]
mysql>

StockPrediction was developed on OSX which differs in file system case sensitivity
from Ubuntu. Java backend uses table names with mixed case (e.g. Table1 and table1), 
this worked without errors on case insensitive platform, but failed on case sensitive 
Linux: "table1" and "Table1" are not the same for Ubuntu mysql.

To solve this one has to either fix Java code and use table name consistently 
Table1/table1 everywhere or follow MySQL documentation and set lower_case_table_names=1 
in my.cnf, http://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html
# vim /etc/mysql/my.cnf

Under [mysqld] add "lower_case_table_names = 1"  

 [mysqld]
 #
 # \* Basic Settings
 #
 lower_case_table_names = 1
# cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf

 (cp is optional, we don't plan to run mysql_install_db)
# service mysql restart
#3. Installing StockPrediction backend
# cd /root
# git clone https://github.com/DongyangY/StockPrediction.git
# cd StockPrediction/Code/Database/Tables

Fix the dump to use InnoDB instead of legacy MyISAM.
# cp StockForecaster.sql StockForecaster.sql.bak
# perl -pi -e 's/ENGINE=MyISAM/ENGINE=InnoDB/g' StockForecaster.sql

Create database and user 
# MYSQL_PWD=$(cat /root/mysql_pwd) mysql -u root

 mysql> create database stockforecaster;
 mysql> create user 'stockforecaster'@'localhost' identified by 'sugus123';
 mysql> grant all on stockforecaster.\* to 'stockforecaster'@'localhost';
 mysql> \q

Test the credentials and load database dump (always drop all tables once you want 
to reload StockForecaster.sql)
# MYSQL_PWD=sugus123 mysql -u stockforecaster stockforecaster

 mysql> use stockforecaster;
 mysql> . StockForecaster.sql
 mysql> show tables;
## Fix Java code (two lines) and compile
# cd /root/StockPrediction
# vim Code/Backend/Source/DatabaseManager.java

Fix credentials:

public static final String USER_NAME = "stockforecaster";
public static final String PASSWORD = "sugus123";

Compile the backend code. Ant or Maven are good, 
but a plain shell script is clean.
# cd /root/StockPrediction
# cat > make.sh << 'EOF'
# !/bin/sh
# author: valdis11235

WORK_DIR=/root/StockPrediction 
BUILD_DIR="$WORK_DIR/build"
[ ! -e $directory ] && mkdir "$BUILD_DIR"
jars="." 
for i in `ls $WORK_DIR/Code/Backend/Library/*jar`
do 
  jars="$jars:$i" 
done
cd "$WORK_DIR/Code/Backend/Source/"
find -name "*.java" > sources.txt
javac -d "$BUILD_DIR" -classpath "$jars" @sources.txt
EOF
# chmod 755 make.sh
# ./make.sh

.. it will prints these warnings, ignore.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

You shall see .class files in build/
# ls -lR build/

stockforecaster
..
## Prepare shell script to run the backend
# cd /root/StockPrediction
# cat > run.sh << 'EOF'
# !/bin/sh
# author: valdis11235

WORK_DIR=/root/StockPrediction
cd $WORK_DIR
BUILD_DIR="$WORK_DIR/build"
jars="."
for i in $(ls $WORK_DIR/Code/Backend/Library/*jar)
do
  jars="$jars:$i"
done
classes="$BUILD_DIR"
echo "$jars:$classes"
java -cp "$jars:$classes" stockforecaster.StockForecaster
EOF
## Run the backend
# chmod 755 run.sh
# ./run.sh

You shall see a lot of messages and finally
---------- Start testing ----------
Output is :
predict day 1: 16.51
---------- Finish testing ----------
---------- Start training ----------
---------- Finish training ----------
---------- Start testing ----------
Input is :
18.450001000000004
15.77
16.309999
16.510000000000005
Output is :
predict day 2: 16.77
---------- Finish testing ----------
^C

You can run this script manually inside 'screen' or with 'nohup' command from /etc/rc.local
to have it reboot resistant.

/valdis

`

**Comment by DongyangY** [comment]
Hi,

Thanks for your suggestions. I know there are some problems here: 1) if you want a second download, you have to clear your previous tables first otherwise there will be duplicate keys. 2) Since we also use machine learning library in C (no suitable one in Java) which is separated from Java main system, thus you have to run C code afterwards to fill some missing tables (this is kind of a messy work though). I will definitely fix these problems when I catch a break.

**Comment by snapo** [comment]
Hi Dong,
Thanks for the answer. I will check if i can solve it with scripting and editing all java source files to fit database integrity/case sensitive. If you could write me up quickly steps in the backend that need to run immediately/everyday/forever/at specific time i could script up something to solve this issue with table drops and so.
By the way... i dont think stocks are predictable, its just peronally for myself to learn a bit more about it.
Best regards

**Comment by DongyangY** [comment]
Hi snapo,
Would you mind sending an email to me (dongyang.yao@rutgers.edu)? I wanna ask you a question in the email - not here. It is very important for me. Thanks for your help.

**Comment by DongyangY** [comment]
Hi snapo,
For the current code, since we use SVM with libsvm-3.20 under the Library folder, after downloading the historical data, the java files generate training and testing files under the stock folder in libsvm-3.20, and then we need to use command line to train it (you will see .sh files there), and finally we can store the results into the database. We need to comment some SVM java code at some steps. You could just comment all SVM code to have a direct view for other functionalities. I will rewrite the whole project to make it easier to use. Thank you again.
